
  # App config
  #server.port=8080
  #spring.application.name=BootMongo
  #server.context-path=/user


# ===============================
# = SPRING
# ===============================
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tkbrew
      username: tk
      password: tk
      authentication-database: admin

# ===============================
# = SPRING DOC
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    cz.klemsa: DEBUG
    org.springframework.web: INFO