version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: 'tkbrew'
    environment:
      MONGO_INITDB_ROOT_USERNAME: tk
      MONGO_INITDB_ROOT_PASSWORD: tk
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
